# XFCE with OpenSSH, zram, and Chromium.
[[ -z ${BUILD_DESKTOP+x} ]] && BUILD_DESKTOP="yes"
[[ -z ${BUILD_MINIMAL+x} ]] && BUILD_MINIMAL="no"
[[ -z ${DESKTOP_ENVIRONMENT+x} ]] && DESKTOP_ENVIRONMENT="xfce"
[[ -z ${DESKTOP_ENVIRONMENT_CONFIG_NAME+x} ]] && DESKTOP_ENVIRONMENT_CONFIG_NAME="config_base"
[[ -z ${ENABLE_SSH+x} ]] && ENABLE_SSH="yes"
[[ -z ${ENABLE_ZRAM+x} ]] && ENABLE_ZRAM="yes"
