# Standard console image with OpenSSH and zram.
[[ -z ${BUILD_DESKTOP+x} ]] && BUILD_DESKTOP="no"
[[ -z ${BUILD_MINIMAL+x} ]] && BUILD_MINIMAL="no"
[[ -z ${ENABLE_SSH+x} ]] && ENABLE_SSH="yes"
[[ -z ${ENABLE_ZRAM+x} ]] && ENABLE_ZRAM="yes"
